// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAMQPzMj97ELnYXWxtfuk0IGW4tt7GOuhA',
    appId: '1:280088572155:web:4fe328ba8f3d476fb3005e',
    messagingSenderId: '280088572155',
    projectId: 'projects-task-management-app',
    authDomain: 'projects-task-management-app.firebaseapp.com',
    storageBucket: 'projects-task-management-app.firebasestorage.app',
    measurementId: 'G-QQ2C5D2B84',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCOypkHj2aJEpm7pEOEiunSptK5e9zHd5U',
    appId: '1:280088572155:android:2269f859ddd9259bb3005e',
    messagingSenderId: '280088572155',
    projectId: 'projects-task-management-app',
    storageBucket: 'projects-task-management-app.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDskRiK-HonUtr-RRgU1PVBSZSRsxGdi0s',
    appId: '1:280088572155:ios:00c5e9e756764d5bb3005e',
    messagingSenderId: '280088572155',
    projectId: 'projects-task-management-app',
    storageBucket: 'projects-task-management-app.firebasestorage.app',
    iosBundleId: 'com.example.projects',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDskRiK-HonUtr-RRgU1PVBSZSRsxGdi0s',
    appId: '1:280088572155:ios:00c5e9e756764d5bb3005e',
    messagingSenderId: '280088572155',
    projectId: 'projects-task-management-app',
    storageBucket: 'projects-task-management-app.firebasestorage.app',
    iosBundleId: 'com.example.projects',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAMQPzMj97ELnYXWxtfuk0IGW4tt7GOuhA',
    appId: '1:280088572155:web:732a8b267acd9103b3005e',
    messagingSenderId: '280088572155',
    projectId: 'projects-task-management-app',
    authDomain: 'projects-task-management-app.firebaseapp.com',
    storageBucket: 'projects-task-management-app.firebasestorage.app',
    measurementId: 'G-BJYVEVD1TE',
  );
}
